include ../../global_config

OBJS = $(OBJDIR)/timestretchplugin.o \
	$(OBJDIR)/timestretchengine.o

OUTPUT = $(PLUGIN_DIR)/timestretch.plugin

include ../../plugin_config




$(OBJDIR)/timestretchplugin.o: timestretchplugin.C
$(OBJDIR)/timestretchengine.o: timestretchengine.C

