include ../../global_config

OBJS = $(OBJDIR)/timestretch.o \
	$(OBJDIR)/timestretchengine.o

OUTPUT = $(PLUGIN_DIR)/timestretch.plugin

include ../../plugin_config




$(OBJDIR)/timestretch.o: timestretch.C
$(OBJDIR)/timestretchengine.o: timestretchengine.C

