include ../../global_config

OBJS = $(OBJDIR)/phaser.o  \
	$(OBJDIR)/phaserwindow.o

OUTPUT = $(PLUGIN_DIR)/phaser.plugin

include ../../plugin_config

$(OBJDIR)/phaser.o: phaser.C
$(OBJDIR)/phaserwindow.o: phaserwindow.C
