include ../../global_config

OBJS := \
	$(OBJDIR)/histogramengine.o \
	$(OBJDIR)/threshold.o \
	$(OBJDIR)/thresholdwindow.o

OUTPUT := $(PLUGIN_DIR)/threshold.plugin


include ../../plugin_config



$(OBJDIR)/threshold.o:        threshold.C
$(OBJDIR)/thresholdwindow.o:  thresholdwindow.C
$(OBJDIR)/histogramengine.o:  histogramengine.C




