include ../../global_config

OBJS = 	$(OBJDIR)/spheretranslate.o  \
	$(OBJDIR)/spheretranslatewin.o

OUTPUT = $(PLUGIN_DIR)/spheretranslate.plugin

include ../../plugin_config

$(OBJDIR)/spheretranslate.o: spheretranslate.C
$(OBJDIR)/spheretranslatewin.o: spheretranslatewin.C
