include ../../global_config

OBJS := $(OBJDIR)/interpolateaudio.o


OUTPUT := $(PLUGIN_DIR)/interpolateaudio.plugin

include ../../plugin_config


$(OBJDIR)/interpolateaudio.o: interpolateaudio.C












