include ../../global_config

OBJS := \
	$(OBJDIR)/blobtracker.o \
	$(OBJDIR)/blobwindow.o

OUTPUT = $(PLUGIN_DIR)/blobtracker.plugin

include ../../plugin_config

$(OBJDIR)/blobtracker.o: blobtracker.C
$(OBJDIR)/blobwindow.o: blobwindow.C


