include ../../global_config

OBJS = $(OBJDIR)/timestretchrt.o \
	../timestretch/$(OBJDIR)/timestretchengine.o

OUTPUT = $(PLUGIN_DIR)/timestretchrt.plugin

include ../../plugin_config


$(OBJDIR)/timestretchrt.o: timestretchrt.C



