include ../../global_config

OBJS = $(OBJDIR)/flanger.o  \
	$(OBJDIR)/flangerwindow.o

OUTPUT = $(PLUGIN_DIR)/flanger.plugin

include ../../plugin_config

$(OBJDIR)/flanger.o: flanger.C
$(OBJDIR)/flangerwindow.o: flangerwindow.C
