include ../../global_config

OBJS = $(OBJDIR)/ivtc.o  \
	$(OBJDIR)/ivtcwindow.o

OUTPUT = $(PLUGIN_DIR)/ivtc.plugin

include ../../plugin_config

$(OBJDIR)/ivtc.o: ivtc.C
$(OBJDIR)/ivtcwindow.o: ivtcwindow.C
