\input texinfo   @c -*-texinfo-*-



@setfilename cinelerra.info
@settitle SECRETS OF CINELERRA


@node TOP
@top

@center SECRETS OF CINELERRA
@center Version 10
@center by Adam Williams
@center Copyright @copyright{} 2011-2025
@center Sections from https://cinelerra-gg.org/download/CinelerraGG_Manual/Contents.html


@include contents.texi
@include about.texi
@include install.texi
@include configure.texi
@include new.texi
@include main_windows.texi
@include load_save.texi
@include navigation.texi
@include editing.texi
@include using_effects.texi
@include project_settings.texi
@include compositing.texi
@include keyframes.texi
@include capturing.texi
@include performance.texi
@include troubleshooting.texi
@include application_notes.texi
@include effects.texi
@include development.texi
@include keyboard.texi








@bye

