include ../../global_config

OBJS = $(OBJDIR)/dot.o  \
	$(OBJDIR)/dotwindow.o \
	$(OBJDIR)/effecttv.o

OUTPUT = $(PLUGIN_DIR)/dot.plugin
CFLAGS += -I../burn


include ../../plugin_config

$(OBJDIR)/dot.o: dot.C
$(OBJDIR)/dotwindow.o: dotwindow.C
$(OBJDIR)/effecttv.o: effecttv.C



