#########################################################
#                         SAMPLERATE CONVERTER
#########################################################

include ../../global_config

OBJS = $(OBJDIR)/cdripper.o \
	$(OBJDIR)/cdripwindow.o

OUTPUT = $(PLUGIN_DIR)/cdripper.plugin

include ../../plugin_config

$(OBJDIR)/cdripper.o: cdripper.C
$(OBJDIR)/cdripwindow.o: cdripwindow.C
