include ../../global_config

OBJS := \
	$(OBJDIR)/edge.o \
	$(OBJDIR)/edgewindow.o

OUTPUT = $(PLUGIN_DIR)/edge.plugin

include ../../plugin_config

$(OBJDIR)/edge.o: edge.C
$(OBJDIR)/edgewindow.o: edgewindow.C


