include ../../global_config

OBJS = 	$(OBJDIR)/scale.o  \
	$(OBJDIR)/scalewin.o

OUTPUT = $(PLUGIN_DIR)/scale.plugin

include ../../plugin_config

$(OBJDIR)/scale.o: scale.C
$(OBJDIR)/scalewin.o: scalewin.C
