include ../../global_config

OBJS := \
	$(OBJDIR)/motion.o \
	$(OBJDIR)/motionwindow.o

OUTPUT := $(PLUGIN_DIR)/motion2.plugin

include ../../plugin_config

$(OBJDIR)/motion.o: motion.C
$(OBJDIR)/motionwindow.o: motionwindow.C
