include ../../global_config

OBJS = $(OBJDIR)/brightness.o  \
	$(OBJDIR)/brightnesswindow.o

OUTPUT = $(PLUGIN_DIR)/brightness.plugin

include ../../plugin_config


$(OBJDIR)/brightness.o: brightness.C
$(OBJDIR)/brightnesswindow.o: brightnesswindow.C
