include ../../global_config

OBJS = $(OBJDIR)/colorbalance.o  \
	$(OBJDIR)/colorbalancewindow.o

OUTPUT = $(PLUGIN_DIR)/colorbalance.plugin

include ../../plugin_config

$(OBJDIR)/colorbalance.o: colorbalance.C
$(OBJDIR)/colorbalancewindow.o: colorbalancewindow.C
