include ../../global_config

OBJS = $(OBJDIR)/rgb601.o  \
	$(OBJDIR)/rgb601window.o

OUTPUT = $(PLUGIN_DIR)/rgb601.plugin

include ../../plugin_config

$(OBJDIR)/rgb601.o: rgb601.C
$(OBJDIR)/rgb601window.o: rgb601window.C
