// The flex lexicon must be generated by another script since
// the tables are in vecctables.c.
// Since it's so hard to generate a flex lexicon from tables the lexicon
// does very little besides tokenizing into a tree.


#include <stdio.h>



int main()
{
	FILE *fd = fopen("lexicon2.f", "w");
	

	fclose(fd);
}
