include ../../global_config

OBJS = $(OBJDIR)/seltempavg.o  \
	$(OBJDIR)/seltempavgwindow.o

OUTPUT = $(PLUGIN_DIR)/seltempavg.plugin

include ../../plugin_config


$(OBJDIR)/seltempavg.o: seltempavg.C
$(OBJDIR)/seltempavgwindow.o: seltempavgwindow.C
