include ../../global_config

OBJS = $(OBJDIR)/compressor.o \
        $(OBJDIR)/compressorgui.o

OUTPUT = $(PLUGIN_DIR)/compressormulti.plugin

include ../../plugin_config


$(OBJDIR)/compressor.o: compressor.C
$(OBJDIR)/compressorgui.o: compressorgui.C
