include ../../global_config

OBJS := $(OBJDIR)/interpolateall.o


OUTPUT := $(PLUGIN_DIR)/interpolateall.plugin

include ../../plugin_config


$(OBJDIR)/interpolateall.o: interpolateall.C












