include ../../global_config

OBJS = $(OBJDIR)/gamma.o  \
	$(OBJDIR)/gammawindow.o

OUTPUT = $(PLUGIN_DIR)/gamma.plugin

include ../../plugin_config

$(OBJDIR)/gamma.o: gamma.C
$(OBJDIR)/gammawindow.o: gammawindow.C
